spring:
  application:
    name: hystrix-request
server:
  context-path: /
  port: 6001

eureka:
  client:
    service-url:
      # 单点配置
      defaultZone: http://127.0.0.1:8001/eureka/

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 2000

custom:
  rest:
    connectionRequestTimeout: 1000
    connectTimeout: 250
    readTimeout: 24000