spring:
  application:
    name: hello-service

server:
  port: 6001

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 120
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/