spring:
  application:
    name: retry-service
  cloud:
    loadbalancer:
      retry:
        enabled: true # 启用重试


server:
  context-path: /
  port: 7004

eureka:
  client:
    service-url:
      # 单点配置
      defaultZone: http://127.0.0.1:8002/eureka/

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 4000

custom:
  rest:
    connectionRequestTimeout: 1000
    connectTimeout: 250
    readTimeout: 3000

client-service:
  ribbon:
    # ConnectTimeout: 250 # 连接超时时间
    # ReadTimeout: 3000 # 处理超时时间
    OkToRetryOnAllOperations: true # 是否对所有的请求进行重试
    MaxAutoRetriesNextServer: 1 # 重试时, 切换实例的次数
    MaxAutoRetries: 5 # 最大重试次数