spring:
  application:
    name: luck-service
  http:
    encoding:
      charset: utf-8
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 80MB
      file-size-threshold: 10
server:
  port: 6002

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 120
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/

