spring:
  application:
    name: feign-consumer
server:
  context-path: /
  port: 6001

eureka:
  client:
    service-url:
      # 单点配置
      defaultZone: http://127.0.0.1:8001/eureka/

feign:
  hystrix:
    enabled: true
  compression:
    request:
      min-request-size: 2048
      mime-types:
        - text/html, application/xml, application/json
    response:
      enabled: true

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000